import Head from 'next/head'
import Image from 'next/image'
import {useEffect, useState} from 'react'
import styles from '../styles/Home.module.css'
import Web3 from 'web3'
import "bootstrap/dist/css/bootstrap.css"
import {Button} from 'react-bootstrap'

export default function Home() {
  const [web3, setWeb3]=useState(null);
  const [address,setAddress]=useState(null);
  function func(){
    window.ethereum ? ethereum.request({method:"eth_requestAccounts"}).then((accounts)=>{setAddress(accounts[0])
      let w3=new Web3(ethereum)
      setWeb3(w3)
      }).catch((err)=>console.log(err))
      :alert("please install metamask")
  }
  useEffect(() => {
    
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>bloggin app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home Page
        </h1>
        <p className={styles.description}>
          connect your meta mask wallet 
        </p>
        <Button onClick={func()}>Connect</Button>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
